[platformio]
src_dir = firmware/esp32
default_envs = esp32_winxu_drive

[env:esp32_winxu_drive]
platform = https://github.com/platformio/platform-espressif32.git#v6.13.0
board = esp32dev
framework = arduino
build_type = release
monitor_speed = 115200
build_unflags =
  -std=gnu++11
build_flags =
  -std=gnu++17
  -DWINXU_LEFT_MOTOR_SIGN=1
  -DWINXU_RIGHT_MOTOR_SIGN=-1
  -DWINXU_SWITCH_ACTIVE_HIGH=1
  -DWINXU_RUNTIME_REVERSE=1
  -Wall
  -Wextra
  -Werror
